name: env_fast_ai
dependencies:
  - python=3.6.1
  - bcolz
  - h5py
  - matplotlib
  - nomkl
  - numpy
  - pandas
  - pip
  - scikit-learn
  - theano
  - pip:
    - image
    - keras==1.2.2
    - tensorflow
